apiVersion: v2
name: hello-world
description: A Hello World app with Redis
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: redis
    version: 17.11.6
    repository: https://charts.bitnami.com/bitnami
