name: Deploy Hello World

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_VERSION: 1.5.0
  HELM_VERSION: 3.12.0

jobs:
  validate-docker-desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}
          
      - name: Validate Chart
        run: |
          helm template ./charts/hello-world | kubectl apply --dry-run=server -f -
          
  deploy-prod:
    needs: validate-docker-desktop
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}

      - name: Install Helm Chart
        run: |
          helm upgrade --install hello-world ./charts/hello-world \
            --kubeconfig <(echo "${{ secrets.KUBE_CONFIG }}")
